import pytest
from app.rag.retriever import KnowledgeBaseRetriever, extract_relevant_evidence_snippet
from app.agents.risk_agent import assess_risks_node
from app.agents.writer_agent import write_proposal_node
from app.agents.state import RFPProposalState


def test_snippet_extraction_same_chunk_multi_section():
    """
    Test A: Same-chunk multi-section evidence.
    Verifies that when a single chunk contains Section A (unrelated capability)
    and Section B (target requirement evidence), the selected snippet comes
    strictly from Section B, never from the beginning of the chunk.
    """
    mixed_chunk = (
        "- Provides immutable audit log records with user identification, client IP, action type, and precise UTC timestamps\n"
        "- Includes security event monitoring and automated alerting on suspicious access attempts\n\n"
        "5. Compliance & Certification Position\n"
        "Demo Company maintains a robust security architecture aligned with SOC 2 Type II principles. "
        "Formal third-party certifications such as ISO/IEC 27001 or FedRAMP are not currently held and require separate qualification where specified."
    )

    req_query = "The vendor MUST hold formal ISO/IEC 27001 certification."
    snippet = extract_relevant_evidence_snippet(req_query, mixed_chunk, status="NON_COMPLIANT")

    assert "audit log" not in snippet.lower(), f"Unrelated audit log text was included in snippet: {snippet}"
    assert "client ip" not in snippet.lower()
    assert "not currently held" in snippet.lower() or "iso/iec 27001" in snippet.lower(), f"Failed to extract certification limitation: {snippet}"


def test_snippet_extraction_negative_evidence_risk_description():
    """
    Test B: Negative evidence in risk description.
    Verifies that for a requirement where the company holds a documented limitation/refusal,
    the risk description generated by assess_risks_node contains the refusal evidence,
    not unrelated preceding text in the same chunk.
    """
    mixed_chunk = (
        "- Features comprehensive audit logging for transactional modifications and security events\n"
        "- Stored with immutable timestamps and user IP addresses\n\n"
        "Third-party compliance notice: Formal ISO/IEC 27001 or FedRAMP certifications are not currently held by the organization."
    )

    state: RFPProposalState = {
        "requirements": [
            {
                "req_code": "REQ-CERT-99",
                "text": "Vendor shall hold active ISO/IEC 27001 certification.",
                "category": "Certification",
                "is_mandatory": True,
                "source_page": 1,
                "source_section": "Security"
            }
        ],
        "compliance_matrix": [
            {
                "req_code": "REQ-CERT-99",
                "status": "NON_COMPLIANT",
                "confidence": 0.90,
                "evidence_text": mixed_chunk,
                "company_source_doc": "Security Governance",
                "citations": [],
                "notes": "Company documentation explicitly states that this feature/standard is unsupported or out of scope."
            }
        ]
    }

    result = assess_risks_node(state)
    risks = result["risks"]

    assert len(risks) == 1
    desc = risks[0]["description"]
    assert "audit logging" not in desc.lower(), f"Risk description contains audit log text: {desc}"
    assert "user ip" not in desc.lower()
    assert "not currently held" in desc.lower() or "iso/iec 27001" in desc.lower(), f"Risk description missing negative evidence: {desc}"


def test_snippet_extraction_positive_evidence_after_unrelated_section():
    """
    Test C: Positive evidence.
    Verifies that when supporting affirmative evidence appears after an unrelated section
    in the same chunk, the correct supporting sentence is selected.
    """
    mixed_chunk = (
        "Exclusions & Out of Scope Capabilities:\n"
        "Mainframe 3270 emulation and COBOL runtime environments are strictly unsupported and out of scope.\n\n"
        "Database Architecture & Automated Backup:\n"
        "Demo Company provides automated daily database backups with a 30-day retention schedule and multi-zone replication."
    )

    req_query = "Automated daily database backups with at least 30-day retention schedule."
    snippet = extract_relevant_evidence_snippet(req_query, mixed_chunk, status="COMPLIANT")

    assert "mainframe" not in snippet.lower()
    assert "cobol" not in snippet.lower()
    assert "30-day retention" in snippet.lower()
    assert "backups" in snippet.lower()


def test_snippet_extraction_unseen_wording_and_domains():
    """
    Test D: Unseen wording and novel domain vocabulary.
    Verifies that generalized token matching and scoring operates accurately
    on completely novel domain requirements and arbitrary section text.
    """
    chunk_text = (
        "Fleet Telematics & Geographic Routing:\n"
        "The logistics engine executes real-time GPS fleet dispatch optimization and geofencing alerts.\n\n"
        "User Identity Services:\n"
        "Provides basic username and password authentication."
    )

    req_query = "Vehicle GPS telematics tracking and geofencing route dispatch."
    snippet = extract_relevant_evidence_snippet(req_query, chunk_text, status="COMPLIANT")

    assert "username and password" not in snippet.lower()
    assert "gps fleet dispatch" in snippet.lower() or "geofencing" in snippet.lower()


def test_snippet_extraction_prefix_invariance():
    """
    Test E: Prefix invariance.
    Verifies that adding unrelated text before or after the relevant evidence
    does not change the selected evidence snippet.
    """
    relevant_part = "Formal FedRAMP High security authorization is not currently held and is out of scope."
    unrelated_part = "Provides responsive web interfaces accessible across standard modern desktop browsers."

    chunk_order_1 = f"{unrelated_part}\n\n{relevant_part}"
    chunk_order_2 = f"{relevant_part}\n\n{unrelated_part}"

    req_query = "FedRAMP High security authorization certification."

    snip1 = extract_relevant_evidence_snippet(req_query, chunk_order_1, status="NON_COMPLIANT")
    snip2 = extract_relevant_evidence_snippet(req_query, chunk_order_2, status="NON_COMPLIANT")

    assert "responsive web" not in snip1.lower()
    assert "responsive web" not in snip2.lower()
    assert "not currently held" in snip1.lower() or "fedramp" in snip1.lower()
    assert "not currently held" in snip2.lower() or "fedramp" in snip2.lower()


def test_section_aware_chunking_numbered_sections():
    """
    Test F: Section-aware chunking.
    Verifies that clearly separated document sections are chunked independently
    with preserved section metadata and never merged into one chunk when each section fits chunk_size.
    """
    doc_text = (
        "DEMO DATA — Synthetic company knowledge.\n\n"
        "1. Role-Based Access Control (RBAC)\n"
        "Demo Company provides granular RBAC across all modules.\n\n"
        "2. Multi-Factor Authentication (MFA)\n"
        "Demo Company enforces MFA for all administrative accounts.\n\n"
        "3. Comprehensive Audit Logging\n"
        "Features immutable audit log records with user identification and timestamps.\n\n"
        "4. Compliance & Certification Position\n"
        "Formal certifications such as ISO/IEC 27001 are not currently held."
    )

    chunks = KnowledgeBaseRetriever.chunk_document_sections(doc_text, chunk_size=600)

    # Must produce separate chunks for separate numbered sections
    assert len(chunks) >= 4, f"Expected at least 4 section chunks, got {len(chunks)}"

    # Verify section 3 chunk does not contain section 4 text
    audit_chunks = [c for c in chunks if "audit log" in c["text"].lower()]
    assert len(audit_chunks) > 0
    assert "not currently held" not in audit_chunks[0]["text"].lower(), "Audit chunk should not contain Section 4 compliance disclaimer"

    # Verify section 4 chunk does not contain section 3 text
    cert_chunks = [c for c in chunks if "not currently held" in c["text"].lower()]
    assert len(cert_chunks) > 0
    assert "audit log" not in cert_chunks[0]["text"].lower(), "Compliance chunk should not contain Section 3 audit logging text"
    assert "Compliance" in cert_chunks[0]["section"]
